# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Web Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v4

      # Set execution policy for the current process to allow scripts to run
      - name: Set execution policy for the current process
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force

      # Unblock scripts that might be downloaded from the internet
      - name: Unblock downloaded scripts
        run: |
          Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter *.ps1 | Unblock-File

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
