# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Web Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v4
      - name: Set execution policy
        shell: powershell
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
